image: node:10.15.3

pipelines:
  default:
    - step:
        name: Build
        caches:
         - node
        script:
         - npm install && npm run build
        artifacts:
         - build
         
    - step:
        name: Deploy to Firebase
        deployment: production
        script:
          - pipe: atlassian/firebase-deploy:0.3.6
            variables:
             FIREBASE_TOKEN: $FIREBASE_TOKEN
